# TODO: update conn info as needed (below setup ported from FE app equivalent)

development:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: spot_me_backend_development
  username: postgres
  host: 127.0.0.1

test:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: spot_me_backend_test
  username: postgres
  host: 127.0.0.1

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: spot_me_backend_production
  username: spot_me_backend
  password: <%= ENV['SPOT_ME_BACKEND_DATABASE_PASSWORD'] %>
